In [6]:
pip install numpy


  Using cached numpy-2.2.6-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.2.6-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

#Practice Problems

###Q1 Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array

In [9]:
arr=[1,2,3,4,5,6]
arr_new = np.array(arr)
arr_new

array([1, 2, 3, 4, 5, 6])

###Q2 Create a 3x3 matrix with values ranging from 2 to 10.

In [10]:
arr=np.array([2,3,4,5,6,7,8,9,10])
arr=arr.reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

###Q3 Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [ ]:
arr=np.zeros(10)
arr[6] = 11
arr

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

###Q4 Write a Python program to reverse an array (first element becomes last).

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr=np.flip(arr)
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

###Q5 Write a Python program to create a 2d array with 1 on the border and 0 inside

In [15]:
arr=np.zeros(25)
arr=arr.reshape(5,5)
arr[0,:]=1
arr[:,0]=1
arr[-1,:]=1
arr[:,-1]=1
arr


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###Q6 Write a Python program to add a border (filled with 0's) around an existing array

In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr=np.pad(arr,pad_width=1,constant_values=0)
arr

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

###Q7 Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [23]:
arr=np.zeros(64)
arr=arr.reshape(8,8)
arr[ : : 2 , 1 : : 2 ] = 1
arr[1 : : 2 ,  : : 2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

###Q8 Write a Python program to convert a list and tuple into arrays.

In [28]:
arr_list = [1,2,3,4,5,6]
arr_list = np.array(arr_list)
print(arr_list)
arr_tuple = (1,2,3,4,5,6)
arr_tuple = np.array(arr_tuple)
print(arr_tuple)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


###Q9 Write a Python program to append values to the end of an array.

In [29]:
arr=np.array([10, 20, 30])
arr= np.append(arr,[40, 50, 60, 70, 80, 90])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

###Q10 Write a Python program to find the real and imaginary parts of an array of complex

In [30]:
arr=np.array([1 + 2j, 3 + 4j, 5 + 6j])
arr_real= arr.real
arr_imag = arr.imag
print(arr_real)
print(arr_imag)


[1. 3. 5.]
[2. 4. 6.]


###Q11 Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.

In [34]:
arr=np.array([1,2,34,4,56,7777])
print(arr.size)
print(arr.itemsize)
print(arr.size * arr.itemsize)

6
8
48


###Q12 Write a Python program to find common values between two arrays.

In [40]:
arr=[]
ar1 = np.array([0 ,10 ,20 ,40, 60])
ar2 = np.array([10, 30, 40])
for i in range (0,ar1.size):
    if ar1[i] in ar2:
        arr.append(ar1[i])
arr=np.unique(arr)
arr

array([10, 40])

###Q13 Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.

In [42]:
arr=[]
ar1=np.array( [ 0 ,10 ,20 ,40 ,60 ,80])
ar2=np.array([10, 30, 40, 50, 70, 90])
for i in range (0,ar1.size):
    if ar1[i] not in ar2:
        arr.append(ar1[i])
arr=np.sort(arr)
arr=np.unique(arr)
arr


array([ 0, 20, 60, 80])

###Q14 Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [45]:
ar1=np.array([ 0 ,10, 20 ,40 ,60 ,80])
ar2=np.array([10, 30, 40, 50, 70])
ar1=np.concatenate((ar1,ar2))
ar1=np.unique(ar1)
ar1=np.sort(ar1)
ar1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

###Q15 Write a Python program compare two arrays using numpy.

In [47]:
ar1=np.array([1,2])
ar2 = np.array([4,5])
print(ar1>ar2)
print(ar1>=ar2)
print(ar1<ar2)
print(ar1<=ar2)



[False False]
[False False]
[ True  True]
[ True  True]


###Q16 Write a Python program to save a NumPy array to a text file.

###Q17 Write a Python program to create a contiguous flattened array.

In [49]:
ar=np.array([[10, 20, 30],
[20 ,40 ,50]])
ar=ar.flatten()
ar

array([10, 20, 30, 20, 40, 50])

###Q18 Write a Python program to change the data type of an array.

In [51]:
ar=np.array([[10, 20, 30],
[20 ,40 ,50]])
print(ar.dtype)
ar=ar.astype('float64')
print(ar.dtype)

int64
float64


###Q19 Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.

In [52]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###Q20 Write a Python program to create an array which looks like below array.


In [53]:

arr = np.tril(np.ones((5, 5)), k=-1)

print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]]


###Q21 Write a Python program to concatenate two 2-dimensional arrays

In [60]:
ans=[]
ar1 = np.array([[0, 1, 3], [5, 7, 9]])
ar2 = np.array([[0, 2, 4], [6, 8, 10]])
ans = np.hstack((ar1, ar2))
print(ans)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


###Q22 Write a Python program to make an array immutable (read-only).